def default_config_service_config():
    return ConfigServiceConfig(
        schema_id="sirellm-runtime",
        fields=[
            RuntimeConfigFieldConfig(
                key="environment",
                value_type="str",
                required=True,
                default="development",
                choices=[
                    "development",
                    "test",
                    "production",
                ],
            ),
            RuntimeConfigFieldConfig(
                key="model_id",
                value_type="str",
                required=True,
                default="sirellm",
            ),
            RuntimeConfigFieldConfig(
                key="max_context_tokens",
                value_type="int",
                required=True,
                default=512,
                minimum=1,
            ),
            RuntimeConfigFieldConfig(
                key="retrieval_top_k",
                value_type="int",
                required=True,
                default=5,
                minimum=1,
                maximum=100,
            ),
            RuntimeConfigFieldConfig(
                key="auth_server_secret",
                value_type="str",
                required=False,
                default=None,
                secret=True,
            ),
        ],
        layers=[
            RuntimeConfigLayerConfig(
                layer_id="runtime",
                priority=100,
                values={},
                metadata={
                    "purpose": (
                        "runtime overrides"
                    ),
                },
                enabled=True,
            ),
        ],
        state_path=(
            "runtime/state/"
            "config.sllmcfg"
        ),
        load_state_on_start=False,
        metadata={
            "profile": "sirellm",
        },
    )
