EXPECTED_FOLDERS = (
    'libs/core/collections',
    'libs/core/math',
    'libs/core/gpu',
    'libs/core/autograd',
    'libs/core/serialization',
    'libs/data/parsers',
    'libs/data/schema',
    'libs/data/adapters',
    'libs/data/streaming',
    'libs/nlp/normalization',
    'libs/nlp/tokenizer',
    'libs/nlp/corpus',
    'libs/neural',
    'libs/transformer',
    'libs/training/losses',
    'libs/training/optimizers',
    'libs/training/schedules',
    'libs/training/batching',
    'libs/training',
    'libs/inference',
    'libs/retrieval/chunking',
    'libs/retrieval/embedding',
    'libs/retrieval/similarity',
    'libs/retrieval/index',
    'libs/retrieval/ranking',
    'libs/rag',
    'libs/safety',
    'libs/protocol',
    'services/api_gateway',
    'services/load_balancer',
    'services/dataset_service',
    'services/preprocessing_service',
    'services/tokenizer_service',
    'services/training_service',
    'services/model_registry',
    'services/inference_service',
    'services/embedding_service',
    'services/retrieval_service',
    'services/rag_service',
    'services/guardrail_service',
    'services/conversation_service',
    'services/monitoring_service',
    'services/auth_service',
    'services/rate_limit_service',
    'services/cache_service',
    'services/logging_service',
    'services/config_service',
    'services/service_discovery',
    'services/event_bus',
    'services/job_queue',
    'services/scheduler_service',
    'services/notification_service',
    'services/audit_service',
    'services/metrics_service',
    'services/tracing_service',
    'services/feature_flag_service',
    'services/secret_service',
    'model_store/manifests',
    'vector_store/siresoft',
    'runtime/networking',
    'runtime/concurrency',
    'runtime/processes',
    'runtime/storage',
    'runtime/lifecycle',
    'runtime/bootstrap',
    'runtime/http',
    'runtime/service_host',
    'runtime/health',
    'runtime/signals',
    'runtime/observability',
    'runtime/diagnostics',
    'runtime/recovery',
    'runtime/maintenance',
    'runtime/control_plane',
    'runtime/composition',
    'runtime/entrypoint',
    'runtime/cli',
    'runtime/server',
    'runtime/daemon',
    'configs/runtime',
    'configs/services',
    'configs/gateway',
    'configs/auth',
    'configs/rate_limit',
    'configs/cache',
    'configs/logging',
    'configs/metrics',
    'configs/tracing',
    'configs/feature_flags',
    'configs/secrets',
    'configs/model_registry',
    'configs/training',
    'configs/inference',
    'configs/retrieval',
    'configs/rag',
    'configs/safety',
    'configs/preprocessing',
    'configs/tokenizer',
    'configs/embedding',
    'configs/conversation',
    'configs/monitoring',
    'configs/service_discovery',
    'configs/event_bus',
    'configs/job_queue',
    'configs/scheduler',
    'configs/notification',
    'configs/audit',
    'configs/load_balancer',
    'configs/config_service',
    'frontend',
    'frontend/src',
    'frontend/src/lib',
    'frontend/src/components',
    'tools',
    'tests',
)

TEST_FILE_BY_FOLDER = {
    'libs/core/collections': 'libs/core/collections/test_collections.py',
    'libs/core/math': 'libs/core/math/test_math.py',
    'libs/core/gpu': 'tests/test_gpu_backend_contract.py',
    'libs/core/autograd': 'libs/core/autograd/test_autograd.py',
    'libs/core/serialization': 'libs/core/serialization/test_serialization.py',
    'libs/data/parsers': 'libs/data/parsers/test_parsers.py',
    'libs/data/schema': 'libs/data/schema/test_schema.py',
    'libs/data/adapters': 'libs/data/adapters/test_adapters.py',
    'libs/data/streaming': 'libs/data/streaming/test_streaming.py',
    'libs/nlp/normalization': 'libs/nlp/normalization/test_normalization.py',
    'libs/nlp/tokenizer': 'libs/nlp/tokenizer/test_tokenizer.py',
    'libs/nlp/corpus': 'libs/nlp/corpus/test_corpus.py',
    'libs/neural': 'libs/neural/test_neural.py',
    'libs/transformer': 'libs/transformer/test_transformer.py',
    'libs/training/losses': 'libs/training/losses/test_losses.py',
    'libs/training/optimizers': 'libs/training/optimizers/test_optimizers.py',
    'libs/training/schedules': 'libs/training/schedules/test_schedules.py',
    'libs/training/batching': 'libs/training/batching/test_batching.py',
    'libs/training': 'libs/training/test_training.py',
    'libs/inference': 'libs/inference/test_inference.py',
    'libs/retrieval/chunking': 'libs/retrieval/chunking/test_chunking.py',
    'libs/retrieval/embedding': 'libs/retrieval/embedding/test_embedding.py',
    'libs/retrieval/similarity': 'libs/retrieval/similarity/test_similarity.py',
    'libs/retrieval/index': 'libs/retrieval/index/test_index.py',
    'libs/retrieval/ranking': 'libs/retrieval/ranking/test_ranking.py',
    'libs/rag': 'libs/rag/test_rag.py',
    'libs/safety': 'libs/safety/test_safety.py',
    'libs/protocol': 'libs/protocol/test_protocol.py',
    'services/api_gateway': 'services/api_gateway/test_api_gateway.py',
    'services/load_balancer': 'services/load_balancer/test_load_balancer.py',
    'services/dataset_service': 'services/dataset_service/test_dataset_service.py',
    'services/preprocessing_service': 'services/preprocessing_service/test_preprocessing_service.py',
    'services/tokenizer_service': 'services/tokenizer_service/test_tokenizer_service.py',
    'services/training_service': 'services/training_service/test_training_service.py',
    'services/model_registry': 'services/model_registry/test_model_registry.py',
    'services/inference_service': 'services/inference_service/test_inference_service.py',
    'services/embedding_service': 'services/embedding_service/test_embedding_service.py',
    'services/retrieval_service': 'services/retrieval_service/test_retrieval_service.py',
    'services/rag_service': 'services/rag_service/test_rag_service.py',
    'services/guardrail_service': 'services/guardrail_service/test_guardrail_service.py',
    'services/conversation_service': 'services/conversation_service/test_conversation_service.py',
    'services/monitoring_service': 'services/monitoring_service/test_monitoring_service.py',
    'services/auth_service': 'services/auth_service/test_auth_service.py',
    'services/rate_limit_service': 'services/rate_limit_service/test_rate_limit_service.py',
    'services/cache_service': 'services/cache_service/test_cache_service.py',
    'services/logging_service': 'services/logging_service/test_logging_service.py',
    'services/config_service': 'services/config_service/test_config_service.py',
    'services/service_discovery': 'services/service_discovery/test_service_discovery.py',
    'services/event_bus': 'services/event_bus/test_event_bus.py',
    'services/job_queue': 'services/job_queue/test_job_queue.py',
    'services/scheduler_service': 'services/scheduler_service/test_scheduler_service.py',
    'services/notification_service': 'services/notification_service/test_notification_service.py',
    'services/audit_service': 'services/audit_service/test_audit_service.py',
    'services/metrics_service': 'services/metrics_service/test_metrics_service.py',
    'services/tracing_service': 'services/tracing_service/test_tracing_service.py',
    'services/feature_flag_service': 'services/feature_flag_service/test_feature_flag_service.py',
    'services/secret_service': 'services/secret_service/test_secret_service.py',
    'model_store/manifests': 'model_store/manifests/test_manifests.py',
    'vector_store/siresoft': 'vector_store/siresoft/test_siresoft_vector_store.py',
    'runtime/networking': 'runtime/networking/test_networking.py',
    'runtime/concurrency': 'runtime/concurrency/test_concurrency.py',
    'runtime/processes': 'runtime/processes/test_processes.py',
    'runtime/storage': 'runtime/storage/test_storage.py',
    'runtime/lifecycle': 'runtime/lifecycle/test_lifecycle.py',
    'runtime/bootstrap': 'runtime/bootstrap/test_bootstrap.py',
    'runtime/http': 'runtime/http/test_http.py',
    'runtime/service_host': 'runtime/service_host/test_service_host.py',
    'runtime/health': 'runtime/health/test_health.py',
    'runtime/signals': 'runtime/signals/test_signals.py',
    'runtime/observability': 'runtime/observability/test_observability.py',
    'runtime/diagnostics': 'runtime/diagnostics/test_diagnostics.py',
    'runtime/recovery': 'runtime/recovery/test_recovery.py',
    'runtime/maintenance': 'runtime/maintenance/test_maintenance.py',
    'runtime/control_plane': 'runtime/control_plane/test_control_plane.py',
    'runtime/composition': 'runtime/composition/test_composition.py',
    'runtime/entrypoint': 'runtime/entrypoint/test_entrypoint.py',
    'runtime/cli': 'runtime/cli/test_cli.py',
    'runtime/server': 'runtime/server/test_server.py',
    'runtime/daemon': 'runtime/daemon/test_daemon.py',
    'configs/runtime': 'configs/runtime/test_runtime_config.py',
    'configs/services': 'configs/services/test_services_config.py',
    'configs/gateway': 'configs/gateway/test_gateway_config.py',
    'configs/auth': 'configs/auth/test_auth_config.py',
    'configs/rate_limit': 'configs/rate_limit/test_rate_limit_config.py',
    'configs/cache': 'configs/cache/test_cache_config.py',
    'configs/logging': 'configs/logging/test_logging_config.py',
    'configs/metrics': 'configs/metrics/test_metrics_config.py',
    'configs/tracing': 'configs/tracing/test_tracing_config.py',
    'configs/feature_flags': 'configs/feature_flags/test_feature_flags_config.py',
    'configs/secrets': 'configs/secrets/test_secrets_config.py',
    'configs/model_registry': 'configs/model_registry/test_model_registry_config.py',
    'configs/training': 'configs/training/test_training_config.py',
    'configs/inference': 'configs/inference/test_inference_config.py',
    'configs/retrieval': 'configs/retrieval/test_retrieval_config.py',
    'configs/rag': 'configs/rag/test_rag_config.py',
    'configs/safety': 'configs/safety/test_safety_config.py',
    'configs/preprocessing': 'configs/preprocessing/test_preprocessing_config.py',
    'configs/tokenizer': 'configs/tokenizer/test_tokenizer_config.py',
    'configs/embedding': 'configs/embedding/test_embedding_config.py',
    'configs/conversation': 'configs/conversation/test_conversation_config.py',
    'configs/monitoring': 'configs/monitoring/test_monitoring_config.py',
    'configs/service_discovery': 'configs/service_discovery/test_service_discovery_config.py',
    'configs/event_bus': 'configs/event_bus/test_event_bus_config.py',
    'configs/job_queue': 'configs/job_queue/test_job_queue_config.py',
    'configs/scheduler': 'configs/scheduler/test_scheduler_config.py',
    'configs/notification': 'configs/notification/test_notification_config.py',
    'configs/audit': 'configs/audit/test_audit_config.py',
    'configs/load_balancer': 'configs/load_balancer/test_load_balancer_config.py',
    'configs/config_service': 'configs/config_service/test_config_service_config.py',
    'frontend': 'tests/test_frontend_shell.py',
    'frontend/src': 'tests/test_frontend_source.py',
    'frontend/src/lib': 'tests/test_frontend_api.py',
    'frontend/src/components': 'tests/test_frontend_components.py',
    'tools': 'tools/test_compute_backend.py',
    'tests': 'tests/test_system_integration.py',
}

CRITICAL_FILES = (
    'frontend/index.html',
    'frontend/package.json',
    'frontend/vite.config.ts',
    'frontend/src/main.tsx',
    'frontend/src/App.tsx',
    'frontend/src/index.css',
    'frontend/src/lib/api.ts',
    'app.py',
    'libs/core/gpu/backend.py',
    'libs/core/gpu/sireikon_cuda.cu',
    'services/api_gateway/routes.py',
    'services/rag_service/service.py',
    'services/guardrail_service/service.py',
    'runtime/composition/builder.py',
    'runtime/entrypoint/main.py',
    'runtime/server/server.py',
    'tools/run_real_pipeline.py',
    'tools/test_compute_backend.py',
    'tools/test_gpu_training.py',
    'tools/test_training_recovery.py',
)

SMOKE_TESTS = (
    'libs/core/autograd/test_autograd.py',
    'libs/nlp/tokenizer/test_tokenizer.py',
    'libs/transformer/test_transformer.py',
    'libs/training/test_training.py',
    'libs/inference/test_inference.py',
    'libs/retrieval/index/test_index.py',
    'libs/rag/test_rag.py',
    'libs/safety/test_safety.py',
    'services/preprocessing_service/test_preprocessing_service.py',
    'services/api_gateway/test_api_gateway.py',
    'services/conversation_service/test_conversation_service.py',
    'runtime/composition/test_composition.py',
    'runtime/entrypoint/test_entrypoint.py',
    'configs/rag/test_rag_config.py',
    'tests/test_frontend_api.py',
    'tests/test_gpu_backend_contract.py',
    'tools/test_compute_backend.py',
)
