def default_monitoring_config():
    return MonitoringConfig(
        probes=[
            MonitoringProbeConfig(
                probe_id="inference-ready",
                service_name=(
                    "inference_service"
                ),
                operation="status",
                required=True,
                readiness_path=[
                    "status",
                    "ready",
                ],
            ),
            MonitoringProbeConfig(
                probe_id="retrieval-ready",
                service_name=(
                    "retrieval_service"
                ),
                operation="status",
                required=True,
                readiness_path=[
                    "status",
                    "ready",
                ],
            ),
            MonitoringProbeConfig(
                probe_id="rag-ready",
                service_name=(
                    "rag_service"
                ),
                operation="status",
                required=True,
                readiness_path=[
                    "status",
                    "ready",
                ],
            ),
            MonitoringProbeConfig(
                probe_id="guardrail-ready",
                service_name=(
                    "guardrail_service"
                ),
                operation="status",
                required=True,
                readiness_path=[
                    "status",
                    "ready",
                ],
            ),
            MonitoringProbeConfig(
                probe_id=(
                    "conversation-ready"
                ),
                service_name=(
                    "conversation_service"
                ),
                operation="status",
                required=False,
                readiness_path=[
                    "status",
                    "ready",
                ],
            ),
        ],
        attach_load_balancer=True,
        metadata={
            "profile": "sirellm",
        },
    )
